on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

name: Continuous Deployment

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v5
